//layout.tsx = the root layout/outer shell Next.js wraps every page in

import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree, Aboreto, Arapey } from "next/font/google";
import "react-day-picker/style.css";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Nav } from "@/components/ui/nav";


const figtree = Figtree({subsets:['latin'],variable:'--font-sans'});

const aboreto = Aboreto({
  subsets: ['latin'],
  variable: "--font-aboreto",
  weight: '400'
});

const arapey = Arapey({
  subsets: ['latin'],
  variable: "--font-arapey",
  weight: '400'
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
    <body 
        className={`${aboreto.variable} ${geistSans.variable} ${geistMono.variable} ${figtree.variable} ${cn(
          "min-h-full flex flex-col antialiased"
        )}`} 
      > 
        <Nav /> 
         <main className="flex-1 flex flex-col">{children}</main> 
        </body>
    </html>
  );
}
